### ISSUE TITLE
Time should be set within bet (multiple choice)

### ISSUE THREAD

**Issue by Baricang** [erixx104/betsy#16]

**Comment by erixx104** [comment]
Multiplechoice with several different times or just a "quick-bet" or "standard-bet" choice?

**Comment by Baricang** [comment]
> Multiplechoice with several different times or just a "quick-bet" or "standard-bet" choice?

I would use the "quick-bet" phrase but with time in brackets:
* Quick-Bet (10s)
* Standard-Bet (30s)
* Gameday-Bet (Bet-Owner should close Bet before game start)

**Comment by erixx104** [comment]
Quick-Bet and Standard-Bet with time in brackets is fine - Gameday-Bet will be postponed ;-)
